#Site configuration
title: Lindsey Pett
name:  Lindsey Pett
author: Lindsey Pett
work:  Ecologist
year: 2019

# Navigation
nav1: "About"
nav2: "Interests"
nav3: "Current Projects"

# Section1
sec1: "Lindsey A. Pett"
sec2: "University of Vermont, Department of Biology
   PhD Candidate"
sec3: "I am interested in aquatic ecosystem stoichiometry, structure, and function, in response to atmospheric deposition. I use the model system Sarracenia purpurea (Northern Pitcher Plant) which is home to a detritus based aquatic ecosystem composed of bacteria, macro-invertebrates, and phytoplankton. Please check out my current research projects, as well as my cohorts. I am working with my advisor Dr. Nicholas Gotelli alongside my labmates: Amanda Northrop, Laure, Ash, Alex Burnham, Emily Beasley, and Raymond Looney"

# Section 2
sec4: "Interests"
sec5: "My current research is centered around atmospheric deposition of nitrogen and phosphorous and the impacts of changes of N:P ratios in aquatic ecosystems"
icon1: "fas fa-code"
icont1: "Write all the code"
icon2: "fa-cubes"
icont2: "Stack small boxes"
icon3: "fa-book"
icont3: "Read books and stuff"
icon4: "fa-coffee"
icont4: "Drink much coffee"
icon5: "fa-bolt"
icont5: "Lightning bolt"
icon6: "fa-users"
icont6: "Shadow clone technique"

# Section 3
sec6: "Current Projects"
sec7: "My current research is centered around atmospheric deposition of nitrogen and phosphorous and the impacts from changes of N:P ratios in aquatic ecosystems"
sec8: "Manipulation of atmospheric deposition of N and P content and N:P ratios"
sec9: "Artificially manipulating the atmospheric deposition entering into the aquatic ecosystem within Sarracenia purpurea. This manipulation will aid in determining how changes in nitrogen, phosphorus and N:P ratios impact stoichiometry, structure, and function."
sec10: "Large spatial scale sampling of Sarracenia purpurea"
sec11: "Sampling S.purpurea over a large gradient of N deposition (0.3 to 115 kg/ha), from Florida to Maine"
sec12: "Phycology of Sarracenia purpurea"
sec13: "Determining changes in algal community structure with varying N:P ratios being inputed into a detrital based aquatic ecosystem with"

# Social Links
#facebook: username
twitter:  Lindsey28387676
#google: username
instagram: patatathefrog
#pinterest: username
#linkedin: username
#youtube: username
#spotify: username
#lastfm: username
github: ulpett
#stackoverflow: username
#quora: username
#reddit: username
#medium: username
#vimeo: username
#keybase: username
email: Lindsey.Pett@uvm.edu

