#Site configuration
title: Lindsey Pett
name:  Lindsey Pett
author: Lindsey Pett
work:  Ecologist, PhD Candidate
year: 2019

# Navigation
nav1: "About"
nav2: "Interests"
nav3: "Current Projects"

# Section1
sec1: "Lindsey A. Pett"
sec2: "University of Vermont, Department of Biology"                                              
sec3: "I investigate the impact of atmospheric nutrient deposition  on aquatic ecosystem stoichiometry, structure, and function. I use the model system Sarracenia purpurea (Northern Pitcher Plant) in my research. S. purpurea is home to a detritus based aquatic ecosystem composed of pitcher prey, bacteria, phytoplankton, and micro and macro-invertebrates.  I work with my advisor Dr. Nicholas Gotelli and my labmates: Amanda Northrop, Lauren Ash, Alex Burnham, Emily Beasley, and Raymond Looney. Check out my research as well as my cohorts'."

# Section 2
sec4: "Interests"
sec5: "My interests lie primarily within wetland and aquatic ecosystems."
icon1: "fas fa-flask"
icont1: "Stoichiometry"
icon2: "fa-ship"
icont2: "Plankton"
icon3: "fa-bug"
icont3: "Aquatic invertebrates"
icon4: "fa-industry"
icont4: "Functional diversity"
icon5: "fa-line-chart"
icont5: "Invertebrate diversity"
icon6: "fa-heart"
icont6: "Carnivorous plants"

# Section 3
sec6: "Current Projects"
sec7: "My stoichiometry work investigates the impact of atmospheric deposition of nitrogen and phosphorous and N:P ratios on aquatic ecosystems."
sec8: "Manipulation of atmospheric deposition of N and P content and N:P ratios"
sec9: "Artificially manipulating the atmospheric deposition entering the aquatic ecosystem within Sarracenia purpurea. This manipulation allows  me to  measure the response of an entire ecosystem's nitrogen phosphorus content and N:P ratios to gradients in deposition as well as the impacts of  stoichiometric changes  on ecosystem structure and function."
sec10: "Large spatial scale sampling of Sarracenia purpurea over varying gradients of N deposition."
sec11: "Sampling S.purpurea over a large gradient of N deposition (0.3 to 115 kg/ha),at 30 sites, from Florida to Maine. Collecting elemental content from plant tissue, pitcher fluid, invertebrates, detritus, and the microbial community. Structural and functional responses were also collected."
sec12: "Phycology of Sarracenia purpurea"
sec13: "Identifying plankton and determining changes in algal community structure both experimentally (manipulating resource ratios) and in natural settings (non-manipulated atmospheric deposition) "

# Social Links
#facebook: username
twitter:  Lindsey28387676
#google: username
instagram: patatathefrog
#pinterest: username
#linkedin: username
#youtube: username
#spotify: username
#lastfm: username
github: ulpett
#stackoverflow: username
#quora: username
#reddit: username
#medium: username
#vimeo: username
#keybase: username
email: Lindsey.Pett@uvm.edu

