# Welcome to Jekyll!

# Website settings
title: "Lindsey Pett"
description: "Lindsey's Website"
keywords: "UVM, nutrient stoichiometry, N:P"
baseurl: "/"
url: "https://lpett.github.io"
# url: "http://127.0.0.1:4000"

# blog img path
img_path: ''

# author
author:
  name: 'Lindsey Pett'
  first_name: 'Lindsey'
  last_name: 'Pett'
  email: 'lpett@uvm.edu'
  facebook_username: 'Lindsey Ann'
  github_username: 'lpett'
  head_img: 'LPbitmoji.jpg'

# social link
jingyu:
  first_name: 'Lindsey'
  last_name: 'Pett'
  description: 'Ecologist.'
  link: 'https://www.uvm.edu/cas/biology/graduate-students'
  email: 'lpett@uvm.edu'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  photo: 'Gallery'
  cv: 'CV'
  link: 'Contact'

# my projects
project:
  saplatform:
    name: 'Sarracenia purpurea Stoichiometry'
    url: '/Jack614/saplatform'
    img: 'static/img/landing/saplatform.png'
  jalpc:
    name: 'Wetland Mesocosm Complex'
    url: '/Jack614/jalpc_jekyll_theme'
    img: 'static/img/landing/jekyll.png'
  angularjs:
    name: 'Lake Champlain Zooplankton'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/angularjs.png'
  Rsser:
    name: 'Adirondack Aquatic Botany'
    url: '/Jack614/Rsser'
    img: 'static/img/landing/rsser.png'

# blog index
index:
  home: 'Home'
  notebook1: 'Stoichiometry Notebook'
  notebook2: 'Naturalist Notebook'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
