# Welcome to Jekyll!

# Website settings
title: "Lindsey Pett"
description: "Lindsey's blog,use Jekyll and github pages."
keywords: "Jack,Jalpc,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "http://www.https://lpett.github.io"
# url: "http://127.0.0.1:4000"

# blog img path
img_path: (LPbitmoji.jpg)

# author
author:
  name: 'Lindsey Pett'
  first_name: 'Lindsey'
  last_name: 'Pett'
  email: 'lpett@uvm.edu'
  facebook_username: 'Lindsey Ann'
  github_username: 'lpett'
  head_img: 'LPbitmoji.jpg'

# social link
jingyu:
  first_name: 'Lindsey'
  last_name: 'Pett'
  description: 'Ecologist'
  link: ''
  email: 'lpett@uvm.edu'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  link: 'Link'

# my projects
project:
  Aquatic Plant Taxonomy:
    name: 'Aquatic Botany'
    url: 
    img: 'aquaticplant.jpg'
  Lake Champlain Zooplankton:
    name: 'Zooplankton of Lake Champlain'
    url: 
    img: 'zoo.jpg'
  Wetland Plant Functional Groups Mesocosm Experiment:
    name: 'Wetland Mesocosm'
    url: 
    img: 'meso.jpg'
  Nutrient Stoichiomety in Northern Pitcher Plants:
    name: 'Sarracenia purpurea Stoichiometry'
    url: 
    img: 'pitcherplant.jpg'

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
