pygments: true
permalink: /otter-pop/:year/:month/:day/:title
markdown: rdiscount
exclude: ['.git']
name: "Lindsey Pett"
description: "The world's greatest biologist"
url: http://tybenz.com/otter-pop
